from time import sleep
from turtle import delay
import pyautogui as pg
import pygetwindow as gw
x=str(input("Please enter your condition:")).lower() 
if x=='morning':
    teams=gw.getWindowsWithTitle('EG TS | Microsoft Teams')[0]
    teams.minimize()
    if  not teams.isMaximized:
        teams.maximize()
        sleep(3)
    sleep(3)
    pg.click(694,22)
    pg.write('/available',1)
    #pg.press('enter')
    pg.click(630,678)
    pg.write('Good morning',0.5)
   # pg.press('enter')
    pg.click(255,277)
    sleep(3)
    pg.click(630,678)
    sleep(3)
    pg.write('Good morning',0.5)
    #pg.press('enter')
    sleep(3)
    pg.click(172,219)
    browser=gw.getWindowsWithTitle('View: Your unsolved tickets – Cybertron International, Inc. – Zendesk - Opera')[0]
    browser.minimize()
    sleep(3)
    browser.maximize()
    browser.activate()
    sleep(3)
    pg.click(1162,120)
    sleep(3)
    #pg.click(1174,151)   
elif x=='available':
    teams=gw.getWindowsWithTitle('EG TS | Microsoft Teams')[0]
    teams.minimize()
    if  not teams.isMaximized:
        teams.maximize()
        sleep(3)
    sleep(3)
    pg.click(694,22)
    pg.write('/available',1)
    pg.press('enter')
    pg.click(630,678)
    pg.write('Back',1)
    pg.press('enter')
    pg.click(255,277)
    sleep(3)
    pg.click(630,678)
    sleep(3)
    pg.write('Back',1)
    pg.press('enter')
    sleep(3)
    pg.click(172,219)
    browser=gw.getWindowsWithTitle('View: Your unsolved tickets – Cybertron International, Inc. – Zendesk - Opera')[0]
    browser.minimize()
    sleep(3)
    browser.maximize()
    browser.activate()
    sleep(3)
    pg.click(1162,120)
    sleep(3)
    pg.click(1174,151)
elif x=='lunch':
    teams=gw.getWindowsWithTitle('EG TS | Microsoft Teams')[0]
    teams.minimize()
    if not teams.isMaximized:
        teams.maximize()
        sleep(6)
    sleep(3)
    pg.click(694,22)
    pg.write('/away',1)
    pg.press('enter')
    pg.click(630,678)
    pg.write('Lunch',1)
    pg.press('enter')
    pg.click(255,277)
    sleep(3)
    pg.click(630,678)
    sleep(3)
    pg.write('Lunch',1)
    pg.press('enter')
    sleep(3)
    pg.click(172,219)
    sleep(3)
    teams.minimize()
    browser=gw.getWindowsWithTitle('View: Your unsolved tickets – Cybertron International, Inc. – Zendesk - Opera')[0]
    browser.minimize()
    sleep(3)
    browser.maximize()
    browser.activate()
    sleep(3)
    pg.click(1162,120)
    sleep(3)
    pg.click(1179,180)
elif x=='break':
    teams=gw.getWindowsWithTitle('EG TS | Microsoft Teams')[0]
    teams.minimize()
    if not teams.isMaximized:
        teams.maximize()
        sleep(3)
    sleep(3)
    pg.click(694,22,2)
    pg.write('/away',1)
    pg.press('enter')
    pg.click(630,678)
    sleep(3)
    pg.write('break',1)
    pg.press('enter')
    pg.click(255,277)
    sleep(3)
    pg.click(630,678)
    sleep(3)
    pg.write('break',1)
    sleep(3)
    pg.press('enter')
    sleep(3)
    pg.clcik(172,219,5)
    browser=gw.getWindowsWithTitle('View: Your unsolved tickets – Cybertron International, Inc. – Zendesk - Opera')[0]
    browser.maximize()
    sleep(3)
    browser.maximize()
    browser.activate()
    sleep(3)
    pg.click(1162,120)
    sleep(3)
    pg.click(1179,180)